### PR TITLE
fix: article view on mini mode

### LINKED ISSUE #1037: Mobile and Web: Article Links Style
IMG_2519

### PR DESCRIPTION
**Pull request by sakul-budhathoki**
fixes #1037

### CODE REVIEW

File: packages/components/socialFeed/RichText/RichText.tsx [hunk 1]
```diff
@@ -34,28 +35,35 @@ export const RichText: React.FC<RichTextProps> = ({
   const [initialHeight, setInitialHeight] = useState(windowHeight);
 
   const handleHeightChange = useCallback((height: number) => {
-    setInitialHeight(height * 2);
```
Comment (sakul-budhathoki) [inline packages/components/socialFeed/RichText/RichText.tsx:37]: @omniwired  I am not sure why ```height * 2``` was used. This makes lots of spacing after the article and before the comment. So, I removed it.

File: packages/components/socialFeed/RichText/utils.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
+export const fixLinkOnHTMLString = (htmlString: string) => {
```
Comment (sakul-budhathoki) [inline packages/components/socialFeed/RichText/utils.ts:1]: This fix has been only implemented for apps only. 
There are few issues on HTML of the article; this should be fixed on the Article creation

```<ul>
  <li>Website: https://foxinodes.net</li>
  <li>
    Discord Server:
    <a href="https://discord.gg/uATTFEFRGx">https://discord.gg/uATTFEFRGx</a>
  </li>
  <li>X (Twitter): https://twitter.com/foxinodes</li>
  <li>
    Medium:
    <a href="https://medium.com/@Foxinodes">https://medium.com/@Foxinodes</a>
  </li>
</ul>
```
Here links are not placed inside <a> tag
Reference post: https://app.teritori.com/feed/post/tori-9edd0333-e427-4b8b-8fa8-49ef72c73b94

Comment (omniwired) [reply packages/components/socialFeed/RichText/utils.ts:1]: thank you for this. I should create a different ticket for the web issue.

**Review by omniwired — APPROVED** [review]
