### PR TITLE
fix(feed): Fix Tip action and TipModal

### LINKED ISSUE #1376: bug(feed): Tip fails
image

### LINKED ISSUE #1389: bug(feed): refresh tip count after tipping on Social Feed

### PR DESCRIPTION
**Pull request by WaDadidou**
### Fixes "Cannot tip"
Closes #1376 
Gno network: https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L119
Other networks: https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L159

image

### Fixes "the Tip amount is not refresh"
Closes #1389 
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L90

### Fixes a wrong Tip amount shown
`tipAmount` was a `string` here, so the `addedAmount` addition results on a broken number displayed
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/hooks/feed/usePost.ts#L74

I used the same pattern as here: https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/utils/social-feed.ts#L123

image

### Fixes this loader that won't stop if the TX fails (Gno Tip also)
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L91

image

### Fixes closing the TipModal, even if Tip fails, to let the Toast Error visible (Gno Tip also)
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L90

### Fixes this error
https://github.com/TERITORI/teritori-dapp/blob/fix-tip/packages/components/socialFeed/SocialActions/TipModal.tsx#L58-L60

image

### CODE REVIEW

File: packages/components/socialFeed/SocialActions/TipButton.tsx [hunk 1]
```diff
@@ -113,17 +113,21 @@ export const TipButton: React.FC<{
...
         postId={postId}
-        onClose={(newTipAmount: number | undefined) => {
+        onClose={(addedTipAmount: number | undefined) => {
           setTipModalVisible(false);
-          newTipAmount && setTipAmountLocal(amount + newTipAmount);
+          addedTipAmount &&
+            setTipAmountLocal(
+              (typeof amount !== "number" ? parseInt(amount, 10) : amount) +
+                addedTipAmount,
+            );
```
Comment (n0izn0iz) [inline packages/components/socialFeed/SocialActions/TipButton.tsx:130]: please don't add a hack and find root cause of why a string is passed

**Review by n0izn0iz — CHANGES_REQUESTED** [review]

File: packages/components/socialFeed/SocialActions/TipButton.tsx (hunk 1 above)
Comment (WaDadidou) [reply packages/components/socialFeed/SocialActions/TipButton.tsx]: https://github.com/TERITORI/teritori-dapp/pull/1387/commits/db6a08fb1ffd5ea9da43bfa210d9e35f2e4e9207

**Review by n0izn0iz — CHANGES_REQUESTED** [review]
I have a full app crash when a decimal number (like `0.42`) is entered as tip amount, it's not present on main

```
Error: Fractional part missing

    at _e.TipModal (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:3706:1087)
    at _e.TipButton (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:3705:1495)
    at div
    at https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:603:1621
    at div
    at https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:603:1621
    at e.FlexRow (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:3247:260)
    at e.SocialCardFooter (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:5133:328)
    at div
```

**Review by MikaelVallenet — DISMISSED** [review]
LGTM

File: packages/components/socialFeed/SocialActions/TipModal.tsx [hunk 2]
```diff
@@ -80,22 +109,18 @@ export const TipModal: React.FC<{
       return;
     }
 
-    const amount = Decimal.fromUserInput(
-      fieldValues.amount,
-      nativeCurrency.decimals,
-    ).atomics;
-
     if (selectedNetworkInfo?.kind === NetworkKind.Gno) {
```
Comment (hthieu1110) [inline packages/components/socialFeed/SocialActions/TipModal.tsx:112]: IMHO, we should handle this in a more consistent and generic way: 

We can have: useSocialFeedTipPostMutation({...})

In in that hook we switch for Teritori, Gno... and other networks later

**Comment by WaDadidou** [comment]
> I have a full app crash when a decimal number (like `0.42`) is entered as tip amount, it's not present on main
> 
> ```
> Error: Fractional part missing
> 
>     at _e.TipModal (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:3706:1087)
>     at _e.TipButton (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:3705:1495)
>     at div
>     at https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:603:1621
>     at div
>     at https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:603:1621
>     at e.FlexRow (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:3247:260)
>     at e.SocialCardFooter (https://deploy-preview-1387--teritori-dapp.netlify.app/_expo/static/js/web/AppEntry-365ba3edc76685e54f8abeac0296fa69.js:5133:328)
>     at div
> ```

Fixed
https://github.com/TERITORI/teritori-dapp/pull/1387/commits/b02a670c922b8eae00cc539935d0830f776c0687
and https://github.com/TERITORI/teritori-dapp/pull/1387/commits/57224f329e98dd96b400d57ec7c105f8f6294e23

File: packages/components/socialFeed/SocialActions/TipModal.tsx (hunk 2 above)
Comment (WaDadidou) [reply packages/components/socialFeed/SocialActions/TipModal.tsx:117]: We could make an exported hook `useSocialFeedTipPostMutation` and handle Gno and Cosmos networks in it, yes.
But not in this PR

**Review by n0izn0iz — APPROVED** [review]
test and reviewed

**Review by MikaelVallenet — APPROVED** [review]

File: packages/components/socialFeed/SocialActions/TipModal.tsx (hunk 2 above)
Comment (WaDadidou) [reply packages/components/socialFeed/SocialActions/TipModal.tsx:117]: We could make an exported hook `useSocialFeedTipPostMutation` and handle Gno and Cosmos networks in it, yes.
But not in this PR
